/*
最近编写nginx模块的时候，发现worker进程老是打印:
2025/02/13 13:11:03[                 ngx_signal_handler,   927]  [notice] 32580#32580: signal 17 (SIGCHLD) received
为了定位
nginx配置方法
worker_rlimit_core  100M;
working_directory   /path/to/cores/;
注意这里一定要保证/path目录有读写权限，否则不会产生coredump文件


也可以进行系统配置，见下面:
ulimit -c 1024(限制文件大小) 或者unlimited ，这个要注意，如果不做限制，coredump文件会很大，吃掉很多磁盘空间

cat /proc/sys/kernel/core_pattern 查看coredump文件存放路径


echo 0 > /proc/sys/kernel/core_uses_pid
echo /var/corefile/core-%e > /path/core_pattern

echo 0 > /proc/sys/kernel/core_uses_pid
echo /var/corefile/core-%e > /proc/sys/kernel/core_pattern

//corefile携带进程号
echo 1 > /proc/sys/kernel/core_uses_pid
echo /var/corefile/core-%e-%p-%t > /proc/sys/kernel/core_pattern

四、gdb调试codedump:
gdb programfile codedumpfile
(gdb) bt



上面两句执行后，可以保证coredump文件为core-nginx

执行成功只有打印了:Segmentation fault (core dumped)才会有coredump文件产生
打印:Segmentation fault 没有打印(core dumped)则不会参数coredump文件



root@root:/var/yyz# cat /proc/sys/kernel/core_pattern
/var/corefile/core-%e
root@root:/var/yyz# rm -rf /var/corefile 
root@root:/var/yyz# ./a.out 
Segmentation fault
root@root:/var/yyz# mkdi
mkdir        mkdirhier    mkdiskimage  
root@root:/var/yyz# mkdir -p /var/corefile
root@root:/var/yyz# ./a.out 
Segmentation fault (core dumped)
root@root:/var/yyz# 

$grep signal error.log
2012/12/24 16:39:56 [alert] 13661#0: worker process 13666 exited on signal 11  没有coredump文件产生

如果在进程退出后，有coredump文件产生，则会打出如下日志：
$grep signal error.log
2012/12/24 16:39:56 [alert] 13661#0: worker process 13666 exited on signal 11 (core dumped) 

四、gdb调试codedump:
gdb programfile codedumpfile
(gdb) bt




2.core文件的名称和生成路径
----------------------------
core文件生成路径:
输入可执行文件运行命令的同一路径下。
 若系统生成的core文件不带其他任何扩展名称，则全部命名为core。新的core文件生成将覆盖原来的core文件。

1）/proc/sys/kernel/core_uses_pid可以控制core文件的文件名中是否添加pid作为扩展。文件内容为1，表示添加pid作为扩展名，生成的core文件格式为core.xxxx；为0则表示生成的core文件同一命名为core。
 可通过以下命令修改此文件：
echo "1" > c

2）proc/sys/kernel/core_pattern可以控制core文件保存位置和文件名格式。
 可通过以下命令修改此文件：
echo "/corefile/core-%e-%p-%t" > core_pattern，可以将core文件统一生成到/corefile目录下，产生的文件名为core-命令名-pid-时间戳
 以下是参数列表:
 %p - insert pid into filename 添加pid
 %u - insert current uid into filename 添加当前uid
 %g - insert current gid into filename 添加当前gid
 %s - insert signal that caused the coredump into the filename 添加导致产生core的信号
%t - insert UNIX time that the coredump occurred into filename 添加core文件生成时的unix时间
%h - insert hostname where the coredump happened into filename 添加主机名
%e - insert coredumping executable name into filename 添加命令名

详细出处参考：http://www.nginx.cn/1521.html

四、gdb调试codedump:
gdb programfile codedumpfile
(gdb) bt



把core-nginx拷贝到nginx可执行文件同一目录下面

root@root:/var/yyz/corefile# gdb --core core-nginx 
GNU gdb (GDB) 7.1
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-slackware-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
[New Thread 32581]
Core was generated by `nginx: worker'.
Program terminated with signal 11, Segmentation fault.
#0  0x0805106a in ?? ()
(gdb) bt
#0  0x0805106a in ?? ()
#1  0x00000000 in ?? ()
(gdb) file ./nginx 
warning: exec file is newer than core file.
Reading symbols from /var/yyz/corefile/nginx...done.
(gdb) bt
#0  0x0805106a in ngx_vslprintf (
    buf=0xbff2d720 "TTP_SERVER_REWRITE_PHASE)\nent_del_timer,    39]  [debug] 32581#32581: *1 < ngx_http_process_request,  2013>  event timer del: 3: 4256695641\ncess_request_headers,  1412]", 
    last=0xbff2de90 "{